### ISSUE TITLE
License mismatch between this repo and actual Portland

### ISSUE THREAD

**Issue by Calandiel** [Scrawk/Proland-To-Unity#2]
According to the license here, Portland is distributed under GPL. To the best of my information, it isn't (or at least isn't anymore).
http://proland.inrialpes.fr/#license
"Proland is now distributed under the BSD 3 free software license, for non-commercial as well as commercial use.".

Should the license here be perhaps adjusted so its the same as that on Prolands website?

**Comment by Scrawk** [comment]
The license here is a copy of the one found in the Proland source code found here

https://gforge.inria.fr/scm/viewvc.php/proland/trunk/README-DISTRIB.TXT?revision=18&view=markup

The bit about the BSD 3 license has been on the website for years and as far as  I am aware no change has been made to the actual license included with the source code.

**Comment by Calandiel** [comment]
I see, thank you for the reply!

On a related note, if someone had Prolands developers agreement to use their code in a commercial product, would you be willing to discuss such use for this repository too?
